import pandas as pd
import numpy as np
import csv
import datetime as dt

# This program tidies up date and time stamps generated by YouTube API e.g. 2022-02-27T22:27:17Z
# and changes to separate time and date columns.

#list of events per year. Each event contain 30 days and each day contains comments
January_events = ["2015-01-", "2016-01-", "2017-01-", "2018-01-", "2019-01-", "2020-01-", "2021-01-", "2022-01-"]
event_no = 0
year = January_events[event_no]


for i in range (0,32):
    date_string = str(year) + str(i) #this line is written for automatic processing of the files per event

    #csv_name = "../YwP/data/Comments 2022/comments" + date_string + ".csv"

    # this csv files contains a column called updated_at which has date and time in the following format
    # e.g. 2022-02-27T22:27:17Z
    # the aim is to create a column for date, a column for time and also separate columns for year, months and date
    # for further analyses

    csv_name = "comments2015-01-30.csv"
    print(csv_name)

    df = pd.read_csv(csv_name, parse_dates=['updated_at'], infer_datetime_format=True, lineterminator='\n')
    df['Year'] = df['updated_at'].map(lambda ts: ts.strftime("%Y"))
    df['Month'] = df['updated_at'].map(lambda ts: ts.strftime("%m"))
    df['Day'] = df['updated_at'].map(lambda ts: ts.strftime("%d"))
    df['Date'] = df['updated_at'].map(lambda ts: ts.strftime("%d-%m-%Y"))
    df['Time'] = df['updated_at'].map(lambda ts: ts.strftime("%H:%M:%S"))

    # This line is written to store the edited CSV files under a separate folder in the pycharm project.
    outfile = open("../CleanYwP/comments" + date_string + "edited.csv", 'wb')
    #outfile = open("comments/comments2015-01-30edited.csv", 'wb')
    df.to_csv(outfile)
    outfile.close()

    del df

print("Fin.")